module.exports.ingredients = [
    "Flour",
    "Salt",
    "Chicken Wings",
    "Pepper",
    "Paprika",
    "Milk",
    "Water",
    "Sugar",
    "Lentils",
    "Rice",
    "Beef",
    "Oil",
    "Chocolate",
    "Butter",
    "Honey",
    "Eggs",
    "Tomatoes",
    "Cucambers",
    "Celery",
    "Onion",
    "Garlic",
    "Mushrooms",
];

module.exports.units = ["g.", "kg", "L", "mL", "Cup", "Tablespoon", "Teaspoon"];

module.exports.dishes = [
    "Chicken Parm",
    "Cereal",
    "Popcorn",
    "Beef Welington",
    "Eggs Benedict",
    "Tomato Soup",
    "Vegetable Salad",
    "Ceaser Salad",
    "Fish & Chpis",
    "Omlette",
    "Steak and eggs",
    "Chilli con Carne",
    "Chocolate Cake",
    "Strawberry Milkshake",
    "Fruit Salad",
    "Hamburger",
    "Spaghetti Meatballs",
    "Chicken Schnitzel",
    "Baked Fish",
    "Eggplant Parm",
    "Matzah Balls Soup",
];
